const quotes = [
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do not watch the clock. Do what it does. Keep going.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Act as if what you do makes a difference. It does.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Believe you can and you're halfway there.",
    "When something is important enough, you do it even if the odds are not in your favor.",
    "You are never too old to set another goal or to dream a new dream.",
    "The best way to predict the future is to create it.",
    "The only way to do great work is to love what you do.",
    "I find that the harder I work, the more luck I seem to have.",
    "Don't be afraid to give up the good to go for the great.",
    "I attribute my success to this: I never gave or took any excuse.",
    "The only place where success comes before work is in the dictionary.",
    "Success usually comes to those who are too busy to be looking for it.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "All progress takes place outside the comfort zone.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The starting point of all achievement is desire.",
    "The road to success and the road to failure are almost exactly the same.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Your time is limited, so don't waste it living someone else's life.",
    "Don't be trapped by dogma – which is living with the results of other people's thinking.",
    "Don't let the noise of others' opinions drown out your own inner voice.",
    "Have the courage to follow your heart and intuition.",
    "Life is what happens when you're busy making other plans.",
    "When you cease to dream you cease to live.",
    "The only impossible journey is the one you never begin.",
    "Only a life lived for others is a life worthwhile.",
    "You only live once, but if you do it right, once is enough.",
    "If life were predictable it would cease to be life, and be without flavor.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life is either a daring adventure or nothing at all.",
    "The purpose of our lives is to be happy.",
    "Life is really simple, but we insist on making it complicated.",
    "May you live all the days of your life.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "Life is what we make it, always has been, always will be.",
    "Life's tragedy is that we get old too soon and wise too late.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    "In the end, we will remember not the words of our enemies, but the silence of our friends.",
    "It is during our darkest moments that we must focus to see the light.",
    "Whoever is happy will make others happy too.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You have enemies? Good. That means you've stood up for something, sometime in your life.",
    "The only way to do great work is to love what you do.",
    "I have learned over the years that when one's mind is made up, this diminishes fear.",
    "Don't judge each day by the harvest you reap but by the seeds that you plant.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The purpose of our lives is to be happy.",
    "You will face many defeats in life, but never let yourself be defeated.",
    "Life is never fair, and perhaps it is a good thing for most of us that it is not.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "The way to get started is to quit talking and begin doing.",
    "Success is how high you bounce when you hit bottom.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Success is not just about making money. It's about making a difference.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Success is not in what you have, but who you are.",
    "The secret of success is to do the common things uncommonly well.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is the sum of small efforts, repeated day-in and day-out.",
    "The only place where success comes before work is in the dictionary.",
    "Success is not about how much money you make; it's about the difference you make in people's lives.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Success is not measured by the position that one has reached in life, but by the obstacles which he has overcome.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Success is not measured by what you accomplish, but by the opposition you have encountered.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Success is not about how much money you make; it's about the difference you make in people's lives.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not a destination, but the road that you're on.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is not something that happens overnight. It's something you build every day.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not in what you have, but who you are.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",

    // Love Quotes
    "Love is composed of a single soul inhabiting two bodies. - Aristotle",
    "To love and be loved is to feel the sun from both sides. - David Viscott",
    "In love, there are no mistakes, only lessons. - Jennifer Aniston",
    "Where there is love there is life. - Mahatma Gandhi",
    "Love is a friendship set to music. - Joseph Campbell",
    "The best thing to hold onto in life is each other. - Audrey Hepburn",
    "You know you're in love when you can't fall asleep because reality is finally better than your dreams. - Dr. Seuss",
    "Love is not only something you feel, it is something you do. - David Wilkerson",
    "The best proof of love is trust. - Joyce Brothers",
    "To love and win is the best thing. To love and lose, the next best. - William Makepeace Thackeray",
    
    // Success Quotes
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The road to success is always under construction. - Lily Tomlin",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The secret to success is to know something nobody else knows. - Aristotle Onassis",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Opportunities don't happen, you create them. - Chris Grosser",
    "Don't be distracted by criticism. Remember--the only taste of success some people have is when they take a bite out of you. - Zig Ziglar",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  
    // Heartbroken Quotes
    "It's better to have loved and lost than never to have loved at all. - Alfred Lord Tennyson",
    "The heart was made to be broken. - Oscar Wilde",
    "Ever has it been that love knows not its own depth until the hour of separation. - Khalil Gibran",
    "A broken heart bleeds tears. - Steve Maraboli",
    "You can’t buy love, but you can pay heavily for it. - Henny Youngman",
    "The saddest thing about love is that not only that it cannot last forever, but that heartbreak is soon forgotten. - William Faulkner",
    "The emotion that can break your heart is sometimes the very one that heals it. - Nicholas Sparks",
    "Hearts will never be practical until they are made unbreakable. - Wizard of Oz",
    "Love is never lost. If not reciprocated, it will flow back and soften and purify the heart. - Washington Irving",
    "I have found the paradox, that if you love until it hurts, there can be no more hurt, only more love. - Mother Teresa",
  
    // Sadness Quotes
    "Tears are words that need to be written. - Paulo Coelho",
    "Every human walks around with a certain kind of sadness. They may not wear it on their sleeves, but it’s there if you look deep. - Taraji P. Henson",
    "The word 'happiness' would lose its meaning if it were not balanced by sadness. - Carl Jung",
    "Sadness flies away on the wings of time. - Jean de La Fontaine",
    "The walls we build around us to keep sadness out also keep out the joy. - Jim Rohn",
    "Heavy hearts, like heavy clouds in the sky, are best relieved by the letting of a little water. - Christopher Morley",
    "Sadness is but a wall between two gardens. - Khalil Gibran",
    "We must understand that sadness is an ocean, and sometimes we drown, while other days we are forced to swim. - R.M. Drake",
    "Melancholy is the happiness of being sad. - Victor Hugo",
    "Sadness gives depth. Happiness gives height. Sadness gives roots. Happiness gives branches. Happiness is like a tree going into the sky, and sadness is like the roots going down into the womb of the earth. Both are needed, and the higher a tree goes, the deeper it goes, simultaneously. The bigger the tree, the bigger will be its roots. In fact, it is always in proportion. That's its balance. - Osho",
  
    // Travel Quotes
    "The world is a book and those who do not travel read only one page. - Saint Augustine",
    "Travel makes one modest. You see what a tiny place you occupy in the world. - Gustave Flaubert",
    "Not all those who wander are lost. - J.R.R. Tolkien",
    "The journey, not the arrival, matters. - T.S. Eliot",
    "To travel is to take a journey into yourself. - Danny Kaye",
    "Travel far enough, you meet yourself. - David Mitchell",
    "We travel not to escape life, but for life not to escape us. - Anonymous",
    "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes. - Marcel Proust",
    "Take only memories, leave only footprints. - Chief Seattle",
    "The world is a book, and those who do not travel read only one page. - Saint Augustine",
    
    // Study Quotes
    "An investment in knowledge pays the best interest. - Benjamin Franklin",
    "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
    "Study without desire spoils the memory, and it retains nothing that it takes in. - Leonardo da Vinci",
    "The more that you read, the more things you will know. The more that you learn, the more places you'll go. - Dr. Seuss",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
    "The beautiful thing about learning is that no one can take it away from you. - B.B. King",
    "Learning is not attained by chance, it must be sought for with ardor and attended to with diligence. - Abigail Adams",
    "The only thing that interferes with my learning is my education. - Albert Einstein",
    "You don't understand anything until you learn it more than one way. - Marvin Minsky",
    "Study while others are sleeping; work while others are loafing; prepare while others are playing; and dream while others are wishing. - William Arthur Ward",
    
    // Additional Quotes for each category (simply add more quotes to each category)
  
    // Love Quotes (Additional)
    "Love is like the wind, you can't see it but you can feel it. - Nicholas Sparks",
    "Love is when the other person's happiness is more important than your own. - H. Jackson Brown Jr.",
    "You don't love someone because they're perfect, you love them in spite of the fact that they're not. - Jodi Picoult",
  
    // Success Quotes (Additional)
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Success is how high you bounce when you hit bottom. - George S. Patton",
    "The starting point of all achievement is desire. - Napoleon Hill",
  
    // Heartbroken Quotes (Additional)
    "The hottest love has the coldest end. - Socrates",
    "It's amazing how someone can break your heart and you can still love them with all the little pieces. - Ella Harper",
    "Hearts live by being wounded. - Oscar Wilde",
  
    // Sadness Quotes (Additional)
    "Our sweetest songs are those that tell of saddest thought. - Percy Bysshe Shelley",
    "The good times of today are the sad thoughts of tomorrow. - Bob Marley",
    "There is no greater sorrow than to recall in misery the time when we were happy. - Dante Alighieri",
  
    // Travel Quotes (Additional)
    "To travel is to live. - Hans Christian Andersen",
    "The journey of a thousand miles begins with a single step. - Lao Tzu",
    "We wander for distraction, but we travel for fulfillment. - Hilaire Belloc",
  
    // Study Quotes (Additional)
    "Education is not the filling of a pail, but the lighting of a fire. - William Butler Yeats",
    "Learning is a treasure that will follow its owner everywhere. - Chinese Proverb",
    "The more I live, the more I learn. The more I learn, the more I realize, the less I know. - Michel Legrand"
  ];
  





const quoteElement = document.getElementById('quote');
const button = document.getElementById('new-quote-button');

button.addEventListener('click', () => {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    quoteElement.textContent = quotes[randomIndex];
});

